### ISSUE TITLE
Skp

### ISSUE THREAD

**Issue by ghost** [shurcooL/Hover#2]
Did you work out a way to convert skp to dae ?

I am playing around with this code and want to add new objects from SketchUp for my kid to learn programming :)

**Comment by dmitshur** [comment]
I believe SketchUp itself can export as .dae. That’s what I did, at least in the version of SketchUp I used, which was some time ago.

**Edit:** Confirmed:

![image](https://user-images.githubusercontent.com/1924134/36335997-0c3112d4-1352-11e8-9092-ea463a34618c.png)

Picking 3D Model from Export lets you export a model as .dae. However, this free version of SketchUp isn't the latest, and I'm not sure if it's still available. I think they moved the free tier to an in-browser version.
