### ISSUE TITLE
 hover--format of the “track1.dat” terrain???

### ISSUE THREAD

**Issue by gjy88** [shurcooL/Hover#3]
I downloaded the example file of “hover,” but I’m having trouble understanding some parts. Specifically, I’m wondering about the format of the “track1.dat” terrain. Could you please provide some guidance on this?

Thank you.

**Comment by dmitshur** [comment]
The track1.dat file uses an internal format of the game whose source code is located in this repository. You can refer to the Go reimplementation [track/track.go](https://github.com/shurcooL/Hover/blob/HEAD/track/track.go), or the original C++ implementation in [HoverSource/common/track.cpp](https://github.com/shurcooL/Hover/blob/HEAD/HoverSource/common/track.cpp). It's not documented beyond that.
